### ISSUE TITLE
Yarn link

### ISSUE THREAD

**Issue by A1450** [VVNoodle/PS5bot#1]
Hey thanks for making this, when I try to run "Yarn link" in the command prompt it says not recongized. Am I doing something wrong?

**Comment by A1450** [comment]
Cool, I'll try that.

**Comment by A1450** [comment]
that worked but now running the bot isn't working.

**Comment by VVNoodle** [comment]
can you elaborate on that?

**Comment by A1450** [comment]
Same issue as before; command prompt doesn't recognize "ps5bot"

**Comment by A1450** [comment]
This was in the first step of setup after installation.

**Comment by Vynxly** [comment]
I second the whole 'ps5bot' no recognized thing. I was trying a bunch of stuff out yesterday to try to get it to link and get working, but to no avail.

**Comment by VVNoodle** [comment]
im looking into this problem, but as a workaround you can go to bin in the project directory and run `./ps5bot` or `ps5bot` there

**Comment by Vynxly** [comment]
> 
> 
> im looking into this problem, but as a workaround you can go to bin in the project directory and run `./ps5bot` or `ps5bot` there

Appreciate the reply, unfortunately, that doesn't appear to work either. I was going to make a new ticket to post this screenshot as it's not really pertaining to the yarn issue anymore, but I just want to leave my cmd log in hopes that it might help you and I'll leave it at that.

I went through a fresh install process, so hopefully this helps in some way- Also, I don't know what that memory leak spam is, only started happening after I uninstalled Node.Js 14+ and installed 12.9. 

![image](https://user-images.githubusercontent.com/35917981/98860987-21d89300-242a-11eb-8bf3-f6a2b4d44ed4.png)

**Comment by A1450** [comment]
I was able to get it to work by manually going into the bin in the Ps5-master folder and running it. Try that.

**Comment by ellamae0821** [comment]
running `./ps5bot` inside the bin worked

**Comment by EchoGnome** [comment]
Did anyone get a ps5?

**Comment by A1450** [comment]
Got it manually... when I checked on the target scraper it was unresponsive.

**Comment by A1450** [comment]
And Walmart got technical difficulties.

**Comment by VVNoodle** [comment]
Yeah, this project is pretty much dead. I should've worked on this at least a month ago, and only work on in-stock updates instead of automating purchases. To add insult to injury, I haven't gotten a ps5. sorry about this everyone and grats to anyone who got it!

**Comment by A1450** [comment]
Why do you think it didn't work?
