### ISSUE TITLE
Select Physical or Digital Edition

### ISSUE THREAD

**Issue by texastoastt** [VVNoodle/PS5bot#10]
Is there a way to set a preference for the Physical edition of the console?

**Comment by texastoastt** [comment]
Just wanted to update that this is only on target, and if you fight the auto-refresh, you can direct it to the physical console page and it continues to work. Just an oddity.

**Comment by patch321** [comment]
you can also replace the url for the version you want in the scrape-target-util.ts file.

**Comment by texastoastt** [comment]
> you can also replace the url for the version you want in the scrape-target-util.ts file.

That's exactly what I was looking for! Thanks!
