### ISSUE TITLE
Missing a `:` in the `config.json` in the docs

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [VVNoodle/PS5bot#5]
In the documentation, the `config.json` file is not valid because of missing a `:` on line `3`. I corrected the issue by using the [JSONLint validator](https://jsonlint.com/).

The right `config.json` should be instead like so:
```
{
  "firstName": "Qwer",
  "lastName": "Ty",
  "phoneNumber": "8011111111",
  "email": "email@example.com",
  "state": "State",
  "city": "Random City",
  "address": "2353 Running Water Ct.",
  "zipCode": "95054",
  "creditCardNumber": "0101101010101",
  "expirationMonth": "10",
  "expirationYear": "2022",
  "cvv": "000",
  "targetEmail": "email2@example.com",
  "targetPassword": "eganz245"
}
```

**Comment by Ampzx** [comment]
Mine has email first then phone numbers then after CVV it has cronjobschedule which yours doesn't. Am I running an old version? I just downloaded this yesterday
