### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by pythonishard** [VVNoodle/PS5bot#8]
I know he posted all the source and files, i just wanna verify its not a keylogger or something

**Comment by mc130h** [comment]
Appears fine to me.

**Comment by Man8earPig** [comment]
Use a virtual credit card and change your password when you're done using it if you're worried. 
There's nothing that I can see in the code that logs your info.

**Comment by pythonishard** [comment]
so then what would happen if i only left the credit card details blank? would i be able to fill it in manually?
